# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\OpenServer\domains\checksum\1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 40, 21, 21))
        self.pushButton.setMinimumSize(QtCore.QSize(21, 21))
        self.pushButton.setMaximumSize(QtCore.QSize(21, 21))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton { background:transparent;}")
        self.pushButton.setText("")
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 100, 203, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(61, 20))
        self.lineEdit.setMaximumSize(QtCore.QSize(61, 20))
        self.lineEdit.setStyleSheet(
            "background-color: rgba(255, 255, 255, 100);\n" "border:1 solid rgb(0,0,0);"
        )
        self.lineEdit.setFrame(False)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(61, 20))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(61, 20))
        self.lineEdit_2.setStyleSheet(
            "background-color: rgba(255, 255, 255, 100);\n" "border:1 solid rgb(0,0,0);"
        )
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(61, 20))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(61, 20))
        self.lineEdit_3.setStyleSheet(
            "background-color: rgba(255, 255, 255, 100);\n" "border:1 solid rgb(0,0,0);"
        )
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_4.addWidget(self.lineEdit_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 211, 40, 16))
        self.label.setMinimumSize(QtCore.QSize(40, 16))
        self.label.setMaximumSize(QtCore.QSize(40, 16))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 30, 30))
        self.label_2.setStyleSheet("")
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 46, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Miriam")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(129, 233, 131, 101))
        self.textEdit_2.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor)
        )
        self.textEdit_2.setStyleSheet(
            "background-color: rgba(255, 255, 255, 100);\n" "border:1 solid rgb(0,0,0);"
        )
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setAcceptRichText(True)
        self.textEdit_2.setObjectName("textEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CheckSum"))
        self.label_3.setText(_translate("MainWindow", "KCV TMK"))
        self.label_4.setText(_translate("MainWindow", "KCV MMK"))
        self.label_5.setText(_translate("MainWindow", "KCV EWK"))
        self.label.setText(_translate("MainWindow", "key num"))
        self.label_6.setText(_translate("MainWindow", "CheckSum"))
